import subprocess


POKEMON_NAMES = [
        "shroodle",
        "Grafaiai",
        "Bramblin",
        "Brambleghast",
        "Toedscool",
        "Toedscruel",
        "Klawf",
        "Capsakid",
        "Scovillain",
        "Rellor",
        "Rabsca",
        "Flittle",
        "Espathra",
        "Tinkatink",
        "Tinkatuff",
        "Tinkaton",
        "Wiglett",
        "Wugtrio",
        "Bombirdier",
        "Finizen",
        "Palafin",
        "Varoom",
        "Revavroom",
        "Cyclizar",
        "Orthworm",
        "Glimmet",
        "Glimmora",
        "Greavard",
        "Houndstone",
        "Flamigo",
        "Cetoddle",
        "Cetitan",
        "Veluza",
        "Dondozo",
        "Tatsugiri-Orange",
        "Annihilape",
        "Clodsire",
        "Farigiraf",
        "Dudunsparce",
        "Kingambit",
        "Great-Tusk",
        "Scream-Tail",
        "Brute-Bonnet",
        "Flutter-Mane",
        "Slither-Wing",
        "Sandy-Shocks",
        "Iron-Treads",
        "Iron-Bundle",
        "Iron-Hands",
        "Iron-Jugulis",
        "Iron-Moth",
        "Iron-Thorns",
        "Frigibax",
        "Arctibax",
        "Baxcalibur",
        "Gimmighoul",
        "Gholdengo",
        "Wo-Chien",
        "Chien-Pao",
        "Ting-Lu",
        "Chi-Yu",
        "Roaring-Moon",
        "Iron-Valiant",
        "Koraidon",
        "Miraidon",
        "Walking-Wake",
        "Iron-Leaves",
        "Dipplin",
        "Poltchageist",
        "Sinistcha",
        "Okidogi",
        "Munkidori",
        "Fezandipiti",
        "Ogerpon",
        "Archaludon",
        "Hydrapple",
        "Gouging-Fire",
        "Raging-Bolt",
        "Iron-Boulder",
        "Iron-Crown",
        "Terapagos",
        "Pecharunt",
        "Tauros-Paldea",
        "Tauros-Paldea-Blaze",
        "Tauros-Paldea-Aqua",
        "Wooper-Paldea",
        "Ursaluna-Bloodmoon",
        "Oinkologne-Female",
        "Maushold-Family-of-Four",
        "Squawkabilly-White-Plumage",
        "Squawkabilly-Blue-Plumage",
        "Squawkabilly-Yellow-Plumage",
        "Palafin-Hero-Form",
        "Tatsugiri-Red",
        "Tatsugiri-Yellow",
        "Dudunsparce-Three-Segment",
        "Gimmighoul-Roaming-Form",
        "Koraidon-Rider-Form",
        "Miraidon-Rider-Form",
        "Ogerpon-Hearthflame-Mask",
        "Ogerpon-Wellspring-Mask",
        "Ogerpon-Cornerstone-Mask",
        "Terapagos-Terastal-Form",
        "Terapagos-Stellar-Form"
    ]

def renamer():
    names = [name.lower() for name in POKEMON_NAMES]
    for i in range(39, 143):
        # Run find_replace {arg1} {arg2} -r '\b(?:shiny-)?$1\.png\b'
        command: str = f"find_replace {i} {names[i-39]} -r '{r"\b(?:shiny-)?$1\.png\b"}'"
        subprocess.run(command, shell=True, check=True)
        #subprocess.run(['find_replace', file, '-r', r'\b(?:shiny-)?' + file + r'\b'])
        #print(command)
    print("Done")
        
        
if __name__ == '__main__':
    renamer()